import Head from "next/head";
import Nav from "../components/Nav";
export default function Home() {
    return(
    <div>
		  <Head>
        
			<title>Login</title>
			<meta name="description" content="Generated by create next app" />
			
           <Nav/>
		  </Head>
		  
		  </div>
	  )
};